name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389

                  - name: Workflow Processor
  # You may pin to the exact commit or the version.
  # uses: unknorg/workflow-preprocessor@f7c0cb1a17d51160fc96e033925bacb8df7fd71f
  uses: unknorg/workflow-preprocessor@1.0.3
  with:
    # The directory containing the templates to use, will not scan subdirectories
    templates-directory: # optional, default is ./src/templates
    # The directory containing the workflows to use, will not scan subdirectories
    workflows-directory: # optional, default is ./src
    # The directory containing the schemas, you can use this to override the default schemas
    schema-directory: # optional, default is /action/schema
    # The directory to output the generated workflows to
    generated-directory: # optional, default is ./generated
    # The log level to use, can be [trace, debug, info, warn, error]
    log-level: # optional, default is info
    # Whether to die when the generated workflow is invalid, per the definition of the schema
    die-when-invalid: # optional, default is true
          
